### ISSUE TITLE
Changing Display Name

### ISSUE THREAD

**Issue by asdihquh2e** [MixV2/EpicResearch#108]
How do I change the display name of the account thats currently logged in? Via the metadata endpoint or is there something else?

**Comment by RiftSTW** [comment]
Added it to my fork not sure when Mix will merge my PR
https://github.com/RiftSTW/EpicResearch/blob/master/docs/account/endpoints/change_account_username.md

**Comment by MixV2** [comment]
Closing as this has been answered.
