### ISSUE TITLE
What is Fortnite's AES keys endpoint?

### ISSUE THREAD

**Issue by Videogamer555** [MixV2/EpicResearch#109]
Ever since Epic started encrypting the in-game memory for Fortnite, the BenBot has been unable to extract the keys from the game, which means the free flow of updated keys posted online by BenBot has stopped. These keys are needed to view all the content of the game, like unreleased weapons, with the software FModel. 

One workaround for this would be to directly download the keys from Epic's server. Does anybody here know the official API endpoint for getting Fortnite AES keys, and the exact method to contact this endpoint?

**Comment by RiftSTW** [comment]
The Main AES Key isn't something you can get from Epic's API that requires reverse engineering. However, you can find some other pak AES Keys from the Calander endpoint: https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/calendar/v1/timeline (Auth required)

**Comment by MixV2** [comment]
Closing as this has been answered.
