### ISSUE TITLE
Will be there docs about downloading/getting list of games?

### ISSUE THREAD

**Issue by DuckerMan** [MixV2/EpicResearch#11]

**Comment by MixV2** [comment]
List of games as in the ones you own or all games that are on EGS?

**Comment by DuckerMan** [comment]
Yep, the games I own

**Comment by MixV2** [comment]
I'll add it at some point, but for now here's the endpoint that allows you to do it: https://launcher-public-service-prod.ol.epicgames.com/launcher/api/public/assets/Windows?label=Live (replacing Windows with whatever platform you want to get the games for)

Make sure to authenticate with launcherAppClient2.

**Comment by DuckerMan** [comment]
Thanks! And how does downloading mechanism work?

**Comment by MixV2** [comment]
Not going to document the downloading process, I suggest you check out the source code of https://github.com/Allar/ue4-mp-downloader and https://github.com/WorkingRobot/FortniteDownloader to get a good understanding of the entire process

**Comment by DuckerMan** [comment]
Thanks anyway, another question: What did I do wrong?

![image](https://user-images.githubusercontent.com/23637939/84860131-2b2a2300-b077-11ea-803c-ca1cac956274.png)

**Comment by MixV2** [comment]
You have to encode the client ID + secret in Base64 in the format of `clientId:secret` and pass it into the Authorization header. So for example with fortnitePCGameClient, the Authorization header would look like:

`basic ZWM2ODRiOGM2ODdmNDc5ZmFkZWEzY2IyYWQ4M2Y1YzY6ZTFmMzFjMjExZjI4NDEzMTg2MjYyZDM3YTEzZmM4NGQ=`

**Comment by DuckerMan** [comment]
Huh, thanks

**Comment by DuckerMan** [comment]
Sorry to bother you, but which client does support `grant_type` password?

**Comment by MixV2** [comment]
none, it was deprecated
