### ISSUE TITLE
QueryProfile

### ISSUE THREAD

**Issue by fowummmmm** [MixV2/EpicResearch#135]
I am getting this response: { "errorCode" : "errors.com.epicgames.common.missing_permission", "errorMessage" : "Sorry your login does not posses the permissions 'fortnite:profile:(accountid):commands ALL' needed to perform the requested operation", "messageVars" : [ "fortnite:profile:(accountid):commands", "ALL" ], "numericErrorCode" : 1023, "originatingService" : "fortnite", "intent" : "prod-live" }

I'm not sure how to fix this issue or what I can do to gain access.

**Comment by xences-valid** [comment]
Hello, it looks like you marked the issue as completed. Do you mind telling me what you did to resolve the issue? I'm on the same page

**Comment by BobC0728** [comment]
same issue.
