### ISSUE TITLE
THANKS GUYS I FINALLY ABLE TO MAKE THIS

### ISSUE THREAD

**Issue by ArabCrew786** [MixV2/EpicResearch#137]
![image](https://github.com/MixV2/EpicResearch/assets/136216042/51cf66f7-52d1-48f0-abc5-1f5716ee9083)

FULL CAPTURE 
FORTNITE ACCOUNT
**steel12@gmail.com:matias12345e**  
displayName: steel 123game
Name: Matias Bonanken
failedLoginAttempts: 0
lastLogin: 2023-07-06
Country: Bolivia
tfaEnabled: False
emailVerified: False
Email: steel12@gmail.com
hasHashedEmail: False
Have STW: Yes
STW Key: []
Has OG Ghoul Trooper: No
Has OG Skull Trooper: No
Account Level: 284
Total Wins: 40
XP: 0
Total Skins: 1
Skins: Raz
Total Gliders: 18
Gliders: [Plunder, Base Jumper, Glider, Equalizer, Treefall, Millennium Falcon, Cinder, Palm Leaf, The Umbrella, Sky Shadow, Downpour, glider_id_284_templefemale, umbrella_season_16, TIE Whisper, Royale Air, CLASSIFIED]
Pickaxes: [Default Pickaxe, Low 'n Slow, Peppermint Pick, Marshy Smasher, Snakebite, Boulder Breakers, Shortbread Slicers, Brute Force, Shadow Slicer, Snowy]
Season Counts: 12
Have BattlePass: No!
Skins StageName (List): [Raz, Raz (Glyph Acolyte), Raz (Glyph Master), Chromium Raz, Runic Raz, Golden Raz]
Skin Rarity: Legendary
Config By 🔥 yashvirthepentester 🔥

### **Now i can crack Fortnite Accounts and Sell**

**Comment by 2ir** [comment]
Lol

**Comment by ArabCrew786** [comment]
> > 
> 
> How did you get account items(skin, ...)?

Check here im a breacher bro 
i breach DATABASES .SQL 
https://t.me/imakeconfigs
