### ISSUE TITLE
Unable to get auth code with Authorization Code

### ISSUE THREAD

**Issue by esfesTheKing** [MixV2/EpicResearch#14]
I was looking around the web and found this repo which can improve my programs exacute time. I am trying for the past 2 days to get an auth code with Authorization Code.
I read the the instructions about 50 times and was still unable to get the auth code.
My question is can you please give an example in some programming language, for example python?

**Comment by esfesTheKing** [comment]
i am getting this message every time:

{
    "errorCode": "errors.com.epicgames.common.not_found",
    "errorMessage": "Sorry the resource you were trying to find could not be found",
    "numericErrorCode": 1004,
    "originatingService": "com.epicgames.account.public",
    "intent": "prod"
}

**Comment by MixV2** [comment]
What issue arises when trying to get an authorisation code exactly?

**Comment by esfesTheKing** [comment]
I was able to figure out how to get it in the end.
Thank you for your research.
I will post a solution later.
I have another question the lookup of accounts by id, how do i look for more than 1 account at a time, and how do i get the name of players whom account is set to private?

**Comment by MixV2** [comment]
Glad you got it working!

For multiple account ID lookups, check out [this guide](https://github.com/MixV2/EpicResearch/blob/master/docs/account/endpoints/get_accounts_by_id.md):
e.g. if you wanted to lookup:
- `4735ce9132924caf8a5b17789b40f79c`
- `3d9c055689d341d9b88a917630a6bdb9`
- `3bebf5cdb9434fcfb455ef4807ae099c`

... the URL for the request would look like: https://account-public-service-prod.ol.epicgames.com/account/api/public/account?accountId=4735ce9132924caf8a5b17789b40f79c&accountId=3d9c055689d341d9b88a917630a6bdb9&accountId=3bebf5cdb9434fcfb455ef4807ae099c

What do you mean by accounts that are set to private? To my knowledge, you should be able to get the account ID from a display name no matter what.

**Comment by esfesTheKing** [comment]
I am getting the display name from an account id, in my testing some of the accounts are set to private. When the account is set to private you are unable to get a diplay name.
Thanks for your replay and for your hard work

**Comment by esfesTheKing** [comment]
And what is the difference between a 'displayName' and an 'externalDisplayName'

**Comment by MixV2** [comment]
I'm unfamiliar with what you mean by accounts being "set to private".  

I believe that the `displayName` is the display name of the Epic account, where the `externalDisplayName` is the display name of an external account (e.g. an XBOX account, PlayStation account, etc..).

**Comment by esfesTheKing** [comment]
i got an error once where i didnt find any displayName, so i went to fortnite tracker to see if there was a problem and it said something like can find an account that was set to private in game. but now i can recreate the issue any longer.
I want to thank you once again for creating this repo and i would like to know if i can help in any way, this repo helped me improve the exaction time of my program to under a minute.

**Comment by esfesTheKing** [comment]
![image](https://user-images.githubusercontent.com/65107119/89346614-0edb5780-d6b2-11ea-8a51-664504c9f3f8.png)

my solution, written in python.

**Comment by MixV2** [comment]
Nice!

Feel free to create a PR if you find anything that isn't already documented.

**Comment by esfesTheKing** [comment]
Is there a way to get a permanent  auth token?

**Comment by MixV2** [comment]
You could use something like device auth to create a set of credentials that can be used to continuously generate an access token.

**Comment by esfesTheKing** [comment]
So there isnt a way to get a permanent access token?

**Comment by MixV2** [comment]
No, access tokens expire after 8 hours.

**Comment by youngchief-btw** [comment]
*For security reasons
