### ISSUE TITLE
Is this approach usable for other epic games?

### ISSUE THREAD

**Issue by barnard09** [MixV2/EpicResearch#21]
Hey, I'm trying to find a way to query servers and their player's info on another game on ark survival which utilises the Epic Online Services. Is it possible using this approach, and could you advise on how to find the client ID / secret? Thanks

**Comment by MixV2** [comment]
Hello! Are you sure Ark uses EOS to find information about player's game and they don't have their own custom way of doing that? If you want to find the client ID + secret of ARK's auth client, you can use [Fiddler](https://www.telerik.com/download/fiddler) and inspect the headers for the HTTP request sent to get an access token.

**Comment by barnard09** [comment]
Hey thanks I'll try that, yeah I'm trying to find the player's that are on a server and their ID.
