### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by rubby-c** [MixV2/EpicResearch#36]
https://github.com/MixV2/EpicResearch/blob/master/docs/auth/grant_types/exchange_code.md

"Send a GET request to https://account-public-service-prod.ol.epicgames.com/account/api/oauth/exchange with a valid Authorization header"

What do I have to use in the Authorization header?

**Comment by MixV2** [comment]
`Authorization: Bearer token` with token being a valid auth token

**Comment by Beat-YT** [comment]
close pls
