### ISSUE TITLE
How do I only get username from id

### ISSUE THREAD

**Issue by Grayson9352** [MixV2/EpicResearch#37]
Im trying to get this https://account-public-service-prod.ol.epicgames.com/account/api/public/account/6c34056253a84d269063194d7a69560d/ but it just tells me Authentication failed. I dont wanna put my password in and stuff bc then itll say all the other stuff. You did say you can just get the user but idk how.

**Comment by MixV2** [comment]
You need a valid auth session to access that endpoint so you will need to login to an Epic account

**Comment by Beat-YT** [comment]
Lmfao

**Comment by Beat-YT** [comment]
Use fortnite API
