### ISSUE TITLE
Can you figure out how to set & see an account's status

### ISSUE THREAD

**Issue by youngchief-btw** [MixV2/EpicResearch#7]
Mainly I want this for Fortnite stuff

**Comment by MixV2** [comment]
What do you mean by "see an account's status"?

**Comment by youngchief-btw** [comment]
In Fortnite, I have seen bots (like verification bots) and such change the status from things like "Playing Battle Royale" to "RANDOM THING HERE"

**Comment by MixV2** [comment]
Oh right, that's XMPP presence. I'll get around to it at some point, but if you are trying to figure out how it works then I recommend you take a look at fortnitepy's code to see how it handles custom presences in the mean time
