### ISSUE TITLE
Q: STW Daily Quest 

### ISSUE THREAD

**Issue by vitorlans** [MixV2/EpicResearch#70]
Hey!

Recently Fortnite stopped request more DailyQuest when I use "ClaimLoginReward", obligating me to sign in mode to get new daily quest

Someone know other mcp that I can also use to refresh/get new DailyQuest, I was investigating to use "RefreshExpeditions" but I don't know what it does or if will help.

Thanks

**Comment by Tectors** [comment]
Why in God's name am I still getting notifications about this.
