### ISSUE TITLE
QueryProfile Request Sample

### ISSUE THREAD

**Issue by System32-0101** [MixV2/EpicResearch#75]
¡Hey!
Im trying to get access to the cosmetics of a player, and more info about a player.
I use axios to post to get the access token, the id, and the name.
So, How is the correct endpoint form and post way to get these info?
I tried the classic QueryProfile?profile=athena giving the userID and:
Header = {
'Content-Type' : "xxx-i-form-urlencoded",
'Authorization': `Bearer ${access_token}`
And no Data or Body (are the same xd)
But the response of that post is something like Authorization error or invalid.
Please help me!!

**Comment by b-lack-jpg** [comment]
same trouble, response says that i have no permission to do this request, any help?

**Comment by b-lack-jpg** [comment]
> You can't get another player's cosmetics

Yup, i know, i got the access code

**Comment by b-lack-jpg** [comment]
> You can't get another player's cosmetics

I'm authorizing through iosclientid and it still says that i have no permissions for doing this

**Comment by xences-valid** [comment]
> You can't get another player's cosmetics

You can, just not everything from their locker. Only some
