### ISSUE TITLE
What is the meaning of "MCP"?

### ISSUE THREAD

**Issue by Bohosul01** [MixV2/EpicResearch#83]
I have done a research about the meaning of "MCP" and I have only found [an Epic Games post](https://www.epicgames.com/fortnite/en-US/news/postmortem-of-service-outage-at-3-4m-ccu) and [an Unreal Tournament bug](https://www.epicgames.com/unrealtournament/forums/unreal-tournament-discussion/ut-development-bug-reports-qa/linux-troubleshooting/389953-ut-could-not-save-profile-with-the-mcp-your-settings-may-be-lost).

I have also visited [this page](https://forums.unrealengine.com/t/gamecenter-guide-working-setup-4-15/90991), which says that there is a DefaultPlatformService entry, in Unreal Engine, which is set by default to "MCP"

**Comment by MixV2** [comment]
Pretty sure it stands for Master Control Program

**Comment by Bohosul01** [comment]
OK, problem solved then
