### ISSUE TITLE
Unknown secret for the client named graphqlWebsite

### ISSUE THREAD

**Issue by woctezuma** [MixV2/EpicResearch#89]
In [Auth Clients](https://github.com/MixV2/EpicResearch/blob/master/docs/auth/auth_clients.md), the client called `graphqlWebsite` has an ID, but its secret is unknown.

![Unknown secret](https://i.ibb.co/DQHWwBn/2021-12-26-14-53-21.png)

1) Does that mean that I can authenticate neither [by authorization code](https://github.com/MixV2/EpicResearch/blob/master/docs/auth/grant_types/authorization_code.md), nor [using client credentials](https://github.com/MixV2/EpicResearch/blob/master/docs/auth/grant_types/client_credentials.md), because both methods would require a secret?

2) Or can I work directly with the authorization code returned by visiting the following URL?
> https://www.epicgames.com/id/api/redirect?clientId=319e1527d0be4457a1067829fc0ad86e&responseType=code

Indeed, I notice that the redirectURL looks like:
> https://graphql.epicgames.com/graphql?code=XXX

So it is enticing to use that XXX code along my queries, but I am not sure whether I would get higher permissions by doing so.

3) Otherwise, is there any other client (with known secret) that I could use to get higher permissions to read data from the API with GraphQL? With the few which I have tried, the POST request times out when I submit the access token in the headers like:

```python
import requests

access_token = "MY_TOKEN"

r = requests.post(
    url="https://graphql.epicgames.com/graphql",
    json={"query": "{ Catalog { searchStore(count:3, start: 1617) { paging {total} elements {title} } } }"},
    headers={"Authorization": f'Bearer {access_token}'},
)
```

whereas this works, but without any higher permission:

```python
import requests

r = requests.post(
    url="https://graphql.epicgames.com/graphql",
    json={"query": "{ Catalog { searchStore(count:3, start: 1617) { paging {total} elements {title} } } }"},
)
```

---

At the end of the day, my goal would be to figure out the way the Chinese leaker fetched the upcoming free games:
These games were not present in the public database, as can be seen [on ScreamDB](https://scream-db.web.app/), so I am very surprised.

![Chinese leaker](https://i.ibb.co/PNW4Vhb/2021-12-27-22-16-35.png)

or the way the French leaker at [dealabs.com](https://www.dealabs.com/bons-plans/--2266665) achieved roughly the same.
It has to be a different way, because he has access to less data: he is missing the game to be given away on December 30.

4) Any piece of advice towards this objective?

**Comment by 47PADO47** [comment]
I don't know if this is what you're searching for, but if you didn't you could take a look here: https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions

**Comment by woctezuma** [comment]
> I don't know if this is what you're searching for, but if you didn't you could take a look here: https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions

Thanks. I know this page, but it is not exhaustive. It is only the public visible of the ~~iceberg~~ database.

**Comment by ToutinRoger** [comment]
It doesn't have a secret as it would just authorize with the client id.

**Comment by woctezuma** [comment]
The thing is I don't even need the client ID to have access to the response for this kind of query:
```
https://graphql.epicgames.com/graphql?query={%20Catalog%20{%20searchStore(namespace:%20%22d5241c76f178492ea1540fce45616757%22,%20start:0,%20count:3)%20{%20paging%20{total}%20elements%20{title%20id}%20}%20}%20}
```

By adding the authorization code as a parameter `&code=XXX`, I am not sure whether I get access to more info. It looks like the parameter is omitted, and I get the same response, no matter the different queries which I try.

I think the proper way would be to get an Access Token. However, when I do this with clients with known ID and SECRET, then I get an empty response to my query with an error telling me that I don't have permissions to access this data.

**Comment by ToutinRoger** [comment]
graphqlWebsite never ever had a secret it would just generate a token
sorry if i'm not understanding but there is no "hidden part of the database"

**Comment by ToutinRoger** [comment]
btw &code=XXX won't do anything due to it not being a authorization endpoint, it only works for requests that need it

**Comment by woctezuma** [comment]
> sorry if i'm not understanding but there is no "hidden part of the database"

There is a hidden part of the database. For instance, let us look at "Salt & Sanctuary" (ID: `d3da89e97256484195736eca8b426c72`):

![ScreamDB](https://i.ibb.co/XxKjQfh/2021-12-29-20-29-30.png)

**Comment by ToutinRoger** [comment]
They.. have some kind of source giving them this information, I highly doubt they got permissions to access the information by themselfs.

**Comment by woctezuma** [comment]
You are certainly right.

I realize that we know the id of tomorrow's game:
```
https://graphql.epicgames.com/graphql?query={%20Catalog%20{%20searchStore(namespace:%20%22d5241c76f178492ea1540fce45616757%22,%20start:0,%20count:100)%20{%20paging%20{total}%20elements%20{title%20id}%20}%20}%20}
```

**Comment by Jaren8r** [comment]
> 3. Otherwise, is there any other client (with known secret) that I could use to get higher permissions to read data from the API with GraphQL? With the few which I have tried, the POST request times out when I submit the access token in the headers like:
> 
> ```python
> import requests
> 
> access_token = "MY_TOKEN"
> 
> r = requests.post(
>     url="https://graphql.epicgames.com/graphql",
>     json={"query": "{ Catalog { searchStore(count:3, start: 1617) { paging {total} elements {title} } } }"},
>     headers={"Authorization": f'Bearer {access_token}'},
> )
> ```
If you're trying to authenticate your account to graphql, you need to add a `Cookie` header to the request with the `EPIC_BEARER_TOKEN` cookie set to any token that belongs to your account. graphql will internally exchange that token with one belonging to the graphqlWebsiteClient.

**Comment by woctezuma** [comment]
> 
> If you're trying to authenticate your account to graphql, you need to add a `Cookie` header to the request with the `EPIC_BEARER_TOKEN` cookie set to any token that belongs to your account. graphql will internally exchange that token with one belonging to the graphqlWebsiteClient.

Thank you! I will try that!
